steps:
# Install dependencies
- name: 'python:3.10'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt', '--user']

# Run tests (if you have tests)
# - name: 'python:3.10'
#   entrypoint: python
#   args: ['-m', 'pytest']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-fitness-trainer:$COMMIT_SHA', '.']
  
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ai-fitness-trainer:$COMMIT_SHA']
  
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'ai-fitness-trainer'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ai-fitness-trainer:$COMMIT_SHA'
  - '--region'
  - 'us-central1'  # Change to your preferred region
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'



options:
  logging: CLOUD_LOGGING_ONLY
# Alternative: Deploy to App Engine
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args:
#   - 'app'
#   - 'deploy'
#   - 'app.yaml'

# Store images
images:
- 'gcr.io/$PROJECT_ID/ai-fitness-trainer:$COMMIT_SHA'

timeout: '1600s'